{"name": "test_sub", "status": "failed", "statusDetails": {"message": "AssertionError: assert -1 == -2", "trace": "self = <pytest_test.calc_test.TestCalc object at 0x000000CFDB6DE5B0>\n\n    def test_sub(self):\n        c=Calc()\n        result=c.sub(2,3)\n>       assert result==-2\nE       assert -1 == -2\n\npytest_test\\calc_test.py:28: AssertionError"}, "attachments": [{"name": "stdout", "source": "4b5319df-6555-4002-8482-a29ffc57e32a-attachment.txt", "type": "text/plain"}], "start": 1628763540126, "stop": 1628763540126, "uuid": "069d0f63-a5d0-4201-b0de-3acbbc894104", "historyId": "ec7ebe2e5a79b81ce066de7a36671d36", "testCaseId": "2c5b8d06c3082db363e0a5f261135a5e", "fullName": "pytest_test.calc_test.TestCalc#test_sub", "labels": [{"name": "parentSuite", "value": "pytest_test"}, {"name": "suite", "value": "calc_test"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DataCenter-Yang"}, {"name": "thread", "value": "29656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_test.calc_test"}]}