{"name": "test_sub", "status": "failed", "statusDetails": {"message": "AssertionError: assert -1 == -2", "trace": "self = <pytest_test.calc_test.TestCalc object at 0x000000F0CE7ED5B0>\n\n    def test_sub(self):\n        c=Calc()\n        result=c.sub(2,3)\n>       assert result==-2\nE       assert -1 == -2\n\npytest_test\\calc_test.py:28: AssertionError"}, "attachments": [{"name": "stdout", "source": "3821faea-186c-46cc-b4ac-8542da5b247d-attachment.txt", "type": "text/plain"}], "start": 1628763513673, "stop": 1628763513674, "uuid": "f793bb45-fb1d-4872-b530-1b9733c82d71", "historyId": "ec7ebe2e5a79b81ce066de7a36671d36", "testCaseId": "2c5b8d06c3082db363e0a5f261135a5e", "fullName": "pytest_test.calc_test.TestCalc#test_sub", "labels": [{"name": "parentSuite", "value": "pytest_test"}, {"name": "suite", "value": "calc_test"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DataCenter-Yang"}, {"name": "thread", "value": "34020-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_test.calc_test"}]}