{"name": "test_sub", "status": "failed", "statusDetails": {"message": "AssertionError: assert -1 == -2", "trace": "self = <pytest_test.calc_test.TestCalc object at 0x0000007C2746D5E0>\n\n    def test_sub(self):\n        c=Calc()\n        result=c.sub(2,3)\n>       assert result==-2\nE       assert -1 == -2\n\npytest_test\\calc_test.py:28: AssertionError"}, "attachments": [{"name": "stdout", "source": "99871fc8-6575-47a1-a3f0-26f85b38f586-attachment.txt", "type": "text/plain"}], "start": 1628762936071, "stop": 1628762936072, "uuid": "1707801b-bc5a-4fa6-a978-7e431321e587", "historyId": "ec7ebe2e5a79b81ce066de7a36671d36", "testCaseId": "2c5b8d06c3082db363e0a5f261135a5e", "fullName": "pytest_test.calc_test.TestCalc#test_sub", "labels": [{"name": "parentSuite", "value": "pytest_test"}, {"name": "suite", "value": "calc_test"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DataCenter-Yang"}, {"name": "thread", "value": "29380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest_test.calc_test"}]}